In [1]:
from ansys.mapdl.core import launch_mapdl
import re
import numpy as np
from random import uniform

path = 'c:\\Users\\ebers\\Simulations\\MRN412\\Testing Scripting'
mapdl = launch_mapdl(run_location=path, jobname='TestingScripting',override=True)




In [12]:
data = [[0.01,0.1525,0.107,70E9,2700,0.33],
        [0.006,0.2935,0.1305,70E9,2700,0.33],
        [0.006,0.3265,0.09,70E9,2700,0.33],
        [0.008,0.189,0.101,70E9,2700,0.33],
        [0.010,0.1844,0.152,70E9,2700,0.33],
        [0.01,0.164,0.122,70E9,2700,0.33],
        [0.01,0.1595,0.0917,70E9,2700,0.33]]

reset = True

if reset:
    RawDataToBeSaved = np.empty((0,14),float)
else:
    RawDataToBeSaved = np.load('RawDataToBeSaved.npy', allow_pickle=True)


for i in data:

    Core_data = i
    
    ## General Setup
    mapdl.clear()
    mapdl.prep7()
    mapdl.units("SI")  # SI - International system (m, kg, s, K).

    ##Geometry
    mapdl.block(0,i[1],0,i[2],0,i[0])
    #mapdl.vplot('all')


    ## Material properties
    mapdl.lesize('ALL',i[0], layer1=1) ### check seeds.

    mapdl.mp('ex',1,i[3])
    mapdl.mp('nuxy',1,i[5])
    mapdl.mp('dens',1,i[4])

    mapdl.et(1, 186)
    mapdl.esize(i[0])
    mapdl.vsweep("all")


    mapdl.mshape(1,'3D')
    mapdl.mshkey(0)
    mapdl.vmesh('all')
    #mapdl.eplot()

    mapdl.run("/SOLU")
    mapdl.antype("MODAL")
    output = mapdl.modal_analysis(nmode=8, freqb=1)

    Frequencies = []

    mapdl.post1()
    for n in range(8):
        resp = mapdl.set(lstep='1',sbstep=str(n+1))
        Frequencies.append(float(resp[153:159]))

    #print(Core_data)
    #RawDataToBeSaved = np.append(RawDataToBeSaved,np.array([Core_data]), axis=0)
    
    print(np.round(Frequencies))

    #if ((i+1)%50)==0:
        #np.save('RawDataToBeSaved',RawDataToBeSaved)

    

[1917. 2221. 4420. 4656. 5547. 6509. 8158. 8980.]
[ 366.  496. 1016. 1076. 1830. 1851. 2075. 2150.]
[ 295.  633.  818. 1320. 1609. 2110. 2656. 3048.]
[1172. 1315. 2908. 3211. 4179. 4950. 5085. 6246.]
[1133. 1509. 2371. 2736. 3148. 4342. 5285. 5299.]
[1573. 1919. 3616. 3686. 4523. 5532. 6928. 7358.]
[ 2040.  2117.  4699.  5494.  6235.  7522.  8266. 10148.]


In [8]:

mapdl.exit()

In [4]:
print(len(RawDataToBeSaved))
print((RawDataToBeSaved))


20
[[4.78409107e-03 3.27633695e-01 9.46642624e-02 1.29149219e+11
  4.67067055e+03 2.28339913e-01 2.41240000e+02 5.16480000e+02
  6.66730000e+02 1.07560000e+03 1.30840000e+03 1.71720000e+03
  2.15960000e+03 2.47810000e+03]
 [5.03462523e-03 4.57737635e-01 3.22641026e-01 9.31516172e+10
  2.65504423e+03 2.83971257e-01 1.30490000e+02 1.46470000e+02
  3.03720000e+02 3.05000000e+02 3.80470000e+02 4.34260000e+02
  5.69530000e+02 6.32010000e+02]
 [7.92810519e-04 7.47271620e-02 4.16192862e-02 3.02415323e+11
  1.04200924e+03 2.94893225e-01 2.49780000e+03 2.77650000e+03
  6.19750000e+03 6.91100000e+03 8.27310000e+03 1.00850000e+04
  1.09910000e+04 1.35550000e+04]
 [7.71256816e-03 5.87232400e-01 3.42392844e-01 4.48355642e+11
  7.15609734e+03 3.15998104e-01 1.82850000e+02 1.92740000e+02
  4.34270000e+02 5.04470000e+02 5.55660000e+02 6.87610000e+02
  7.79920000e+02 9.62910000e+02]
 [1.15660590e-03 3.83433175e-02 2.18838462e-02 4.01860365e+11
  7.27501526e+03 3.41114821e-01 6.02780000e+03 6.36990000e+

In [10]:
### This is to Clear the data

np.save('RawDataToBeSaved',np.empty([1,14]))
StoredData = np.load('RawDataToBeSaved.npy')
print(StoredData)

[[7.18273084e-03 1.04723189e+00 4.34438596e-01 5.37042989e+10
  2.73157180e+03 2.81172777e-01 2.99840000e+01 4.46160000e+01
  8.32220000e+01 9.59470000e+01 1.60850000e+02 1.61300000e+02
  1.82450000e+02 1.99670000e+02]]
